现在的代码如下：
steps:
# Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
- uses: actions/checkout@v4
with:
# if your default branches is not master, please change it here
ref: master

  - name: Cache Data Files
    if: inputs.save_data_in_github_cache
    uses: actions/cache@v4
    with:
      path: |
        activities
        assets
        GPX_OUT
        TCX_OUT
        FIT_OUT
        Workouts
        run_page/data.db
        src/static/activities.json
        imported.json
      key: ${{ inputs.data_cache_prefix }}-${{ github.sha }}-${{ github.run_id }}
      restore-keys: |
        ${{ inputs.data_cache_prefix }}-${{ github.sha }}-
        ${{ inputs.data_cache_prefix }}-

  - name: Setup Node.js environment
    uses: actions/setup-node@v4
    with:
      node-version: '20'
  - name: Enable corepack
    run: corepack enable

  - name: Get pnpm store directory
    shell: bash
    run: |
      echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

  - uses: actions/cache@v4
    name: Setup pnpm cache
    with:
      path: ${{ env.STORE_PATH }}
      key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
      restore-keys: |
        ${{ runner.os }}-pnpm-store-
